---
blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹ğŸ¾ Question
    about: Use this to ask a question about this project
    url: https://github.com/orgs/stackabletech/discussions/new?category=q-a
  - name: ğŸš€ Feature Requests and other things
    about: Open an issue with your feature request or any other issue not covered elsewhere
    url: https://github.com/stackabletech/operator-rs/issues/new
