---
blank_issues_enabled: true
contact_links:
  - name: Feature request
    about: ğŸš€ Suggest an idea for this project
    url: https://github.com/stackabletech/operator-rs/discussions/new?category=ideas
  - name: ğŸ™‹ğŸ¾ Question
    about: Use this to ask a question about this project
    url: https://github.com/stackabletech/operator-rs/discussions/new?category=q-a
  - name: Other issue
    about: Open an issue that doesn't fit any other category
    url: https://github.com/stackabletech/operator-rs/issues/new
